# Numpy introduction

In [48]:
#pip install numpy

In [49]:
import numpy as np

# What is an array?
An array is a data structure in programming that stores a collection of elements, typically of the same data type, in a contiguous block of memory. It is a fundamental concept in many programming languages, including Python, and is used extensively in scientific computing, data analysis, and machine learning.

In Python, the NumPy library provides support for arrays and enables efficient numerical operations on them. NumPy arrays are more efficient than Python lists for numerical operations because they are implemented in C and allow for vectorized operations.

In [50]:
a = np.arange(6)
print(a)
a.shape

[0 1 2 3 4 5]


(6,)

In [51]:
a2 = a[np.newaxis, :]
print(a2)
a2.shape

[[0 1 2 3 4 5]]


(1, 6)

In [52]:
a3 = a2[np.newaxis,:]
print(a3)
a3.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

---

# Creating array with numpy

In [53]:
a = np.array([1, 2, 3,4, 5, 6,7])
b = np.array([[1,2,3,4,5,6,7],[4,5,6,7,8,9,10]])

In [54]:
type(a), type(b)

(numpy.ndarray, numpy.ndarray)

In [55]:
a.dtype

dtype('int64')

In [56]:
print(a)
a.shape

[1 2 3 4 5 6 7]


(7,)

In [57]:
print(b)
b.shape

[[ 1  2  3  4  5  6  7]
 [ 4  5  6  7  8  9 10]]


(2, 7)

# initialize array

In [58]:
zeros = np.zeros((3,4)) # (rows, columns)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
zeros.dtype

dtype('float64')

In [60]:
np.ones((3,4)) # (rows, columns)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [61]:
full = np.full((3,4), 5) # (rows, columns)
full

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [62]:
identity = np.eye(3) # identity matrix

# array attributes

In [63]:
a.shape

(7,)

In [64]:
len(a)

7

In [67]:
a.ndim, b.ndim # number of dimensions

(1, 2)

In [70]:
a.size, b.size # number of elements

(7, 14)

In [71]:
a.ndim

1

# Basic opreations

In [72]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [73]:
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8,  9, 10]])

In [76]:
g = a-b
g

array([[ 0,  0,  0,  0,  0,  0,  0],
       [-3, -3, -3, -3, -3, -3, -3]])

In [77]:
g = a+b
g

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [78]:
g = a*b
g

array([[ 1,  4,  9, 16, 25, 36, 49],
       [ 4, 10, 18, 28, 40, 54, 70]])

In [79]:
g = a/b
g

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
        0.66666667, 0.7       ]])

In [81]:
# square of each element
g = a**2
g 

array([ 1,  4,  9, 16, 25, 36, 49])