# Numpy (part-2)

In [18]:
import numpy as np

In [19]:
empty = np.empty((2, 3))
print(empty)
print("---------------")
print(empty[0])

[[0.0e+000 4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323 2.5e-323]]
---------------
[0.e+000 5.e-324 1.e-323]


In [20]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [21]:
even = np.arange(0, 23, 2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [22]:
# array of odd numbers from 1 to 23
odd = np.arange(1, 24, 2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [23]:
# specific diffrerence between numbers
diff = np.arange(0, 23, 3)
diff

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [24]:
lin = np.linspace(0, 10, 5)
lin

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
# define the dtype of array
lin = np.ones(2, dtype=np.int64)
lin

array([1, 1])

In [28]:
# sorting an array
arr = np.array([3, 1, 2,6, 5, 4,8, 7])
arr

array([3, 1, 2, 6, 5, 4, 8, 7])

In [29]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
# Concatenating two arrays
c = np.concatenate((a, b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Concatenate 2D array

In [33]:
x = np.array([[1, 2], [3,4]])
y = np.array([[5, 6]])
# Concatenating along the first axis (rows)
z = np.concatenate((x, y))
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
w = np.array([[1, 2], [3, 4]])


In [36]:
z1 = np.concatenate((x,w))
z1

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [37]:
# create a 3d array
x = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [40]:
x.shape

(2, 2, 2)

In [38]:
x.ndim

3

In [39]:
x.size

8

In [41]:
x = np.reshape(x, (2, 4))
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
# create a 1d array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a


array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# create a 2d array from a 1d array
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [46]:
# create a 3D array
c = b[np.newaxis, :]
c


array([[[1, 2, 3, 4, 5, 6, 7, 8]]])

# Indexing and slicing

In [47]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
a[2]

np.int64(3)

In [50]:
a[2:5]

array([3, 4, 5])

In [52]:
a[-4:]

array([5, 6, 7, 8])

In [53]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
b[1:, 1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [56]:
b[b < 5]  # greater greater than 5

array([1, 2, 3, 4])

In [57]:
b[b%2 == 0]  # even numbers

array([ 2,  4,  6,  8, 10, 12])

In [59]:
# use two conditions
b[((b>2)& (b<11))]

array([ 3,  4,  5,  6,  7,  8,  9, 10])