# Numpy Indexing and Slicing

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
a[-1]

np.int64(7)

In [5]:
b = np.arange(0,12,2)
b

array([ 0,  2,  4,  6,  8, 10])

In [6]:
c = b.reshape(2,3)
c

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [7]:
c[0]

array([0, 2, 4])

In [8]:
c[c<5]

array([0, 2, 4])

---
# making an array form a data or another array

In [9]:
a = np.arange(0,222,5)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [10]:
arr1 = a[40:45]
arr1

array([200, 205, 210, 215, 220])

In [11]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([8,9,10,11,12,13,14])

In [12]:
c = np.vstack((a,b))
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [13]:
b = np.hstack((a,b))
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

---
# Matrix or Matrices

In [14]:
# create a 2-D matrix
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
# create a matrix of big dimension
b = np.arange(0,100,2).reshape(5,10)
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [20]:
# slicing a matrix
c = b[1:3,3:5]
c

array([[26, 28],
       [46, 48]])

In [21]:
b.max()

np.int64(98)

In [22]:
b.min()

np.int64(0)

In [23]:
b.sum()

np.int64(2450)

In [28]:
m = np.arange(0,20,2).reshape(5,2)
m

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [30]:
m + np.array([20,22])

array([[20, 24],
       [24, 28],
       [28, 32],
       [32, 36],
       [36, 40]])

In [32]:
np.vstack((m, np.array([42,44])))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [42, 44]])

In [33]:
np.flip(b)

array([[98, 96, 94, 92, 90, 88, 86, 84, 82, 80],
       [78, 76, 74, 72, 70, 68, 66, 64, 62, 60],
       [58, 56, 54, 52, 50, 48, 46, 44, 42, 40],
       [38, 36, 34, 32, 30, 28, 26, 24, 22, 20],
       [18, 16, 14, 12, 10,  8,  6,  4,  2,  0]])